// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package pgdb

import (
	"context"
)

const login = `-- name: Login :one
SELECT 
name,
role,
email
FROM admin
WHERE id = $1 OR email = $2
LIMIT 1
`

type LoginParams struct {
	ID    int32  `json:"id"`
	Email string `json:"email"`
}

type LoginRow struct {
	Name  string `json:"name"`
	Role  string `json:"role"`
	Email string `json:"email"`
}

func (q *Queries) Login(ctx context.Context, arg LoginParams) (LoginRow, error) {
	row := q.db.QueryRow(ctx, login, arg.ID, arg.Email)
	var i LoginRow
	err := row.Scan(&i.Name, &i.Role, &i.Email)
	return i, err
}
