// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package pgdb

import (
	"context"
)

const login = `-- name: Login :one
SELECT id, name, role, email, password FROM admin
WHERE id = $1 OR email = $2
LIMIT 1
`

type LoginParams struct {
	ID    int32  `json:"id"`
	Email string `json:"email"`
}

func (q *Queries) Login(ctx context.Context, arg LoginParams) (Admin, error) {
	row := q.db.QueryRow(ctx, login, arg.ID, arg.Email)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Email,
		&i.Password,
	)
	return i, err
}
