// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: carousel.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCarousel = `-- name: CreateCarousel :one
INSERT INTO carousels (
    institute_id,
    title,
    is_active
) VALUES (
    $1, $2, $3
)
RETURNING id, institute_id, title, is_active, created_at
`

type CreateCarouselParams struct {
	InstituteID int32       `json:"institute_id"`
	Title       pgtype.Text `json:"title"`
	IsActive    pgtype.Bool `json:"is_active"`
}

func (q *Queries) CreateCarousel(ctx context.Context, arg CreateCarouselParams) (Carousel, error) {
	row := q.db.QueryRow(ctx, createCarousel, arg.InstituteID, arg.Title, arg.IsActive)
	var i Carousel
	err := row.Scan(
		&i.ID,
		&i.InstituteID,
		&i.Title,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCarousel = `-- name: DeleteCarousel :exec
DELETE FROM carousels
WHERE id = $1
`

func (q *Queries) DeleteCarousel(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCarousel, id)
	return err
}

const getCarousel = `-- name: GetCarousel :one
SELECT id, institute_id, title, is_active, created_at
FROM carousels
WHERE id = $1 AND institute_id = $2
LIMIT 1
`

type GetCarouselParams struct {
	ID          int32 `json:"id"`
	InstituteID int32 `json:"institute_id"`
}

func (q *Queries) GetCarousel(ctx context.Context, arg GetCarouselParams) (Carousel, error) {
	row := q.db.QueryRow(ctx, getCarousel, arg.ID, arg.InstituteID)
	var i Carousel
	err := row.Scan(
		&i.ID,
		&i.InstituteID,
		&i.Title,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getCarouselsByInstitute = `-- name: GetCarouselsByInstitute :many
SELECT id, institute_id, title, is_active, created_at
FROM carousels
WHERE institute_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetCarouselsByInstitute(ctx context.Context, instituteID int32) ([]Carousel, error) {
	rows, err := q.db.Query(ctx, getCarouselsByInstitute, instituteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Carousel{}
	for rows.Next() {
		var i Carousel
		if err := rows.Scan(
			&i.ID,
			&i.InstituteID,
			&i.Title,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCarousel = `-- name: UpdateCarousel :one
UPDATE carousels
SET
    title = $2,
    is_active = $3
WHERE id = $1
RETURNING id, institute_id, title, is_active, created_at
`

type UpdateCarouselParams struct {
	ID       int32       `json:"id"`
	Title    pgtype.Text `json:"title"`
	IsActive pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdateCarousel(ctx context.Context, arg UpdateCarouselParams) (Carousel, error) {
	row := q.db.QueryRow(ctx, updateCarousel, arg.ID, arg.Title, arg.IsActive)
	var i Carousel
	err := row.Scan(
		&i.ID,
		&i.InstituteID,
		&i.Title,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
