// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: carousel_photos.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCarouselPhoto = `-- name: CreateCarouselPhoto :one
INSERT INTO carousel_photos (
    carousel_id,
    photo_id,
    display_text,
    display_order
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, carousel_id, photo_id, display_text, display_order, created_at
`

type CreateCarouselPhotoParams struct {
	CarouselID   int32       `json:"carousel_id"`
	PhotoID      int32       `json:"photo_id"`
	DisplayText  pgtype.Text `json:"display_text"`
	DisplayOrder pgtype.Int4 `json:"display_order"`
}

func (q *Queries) CreateCarouselPhoto(ctx context.Context, arg CreateCarouselPhotoParams) (CarouselPhoto, error) {
	row := q.db.QueryRow(ctx, createCarouselPhoto,
		arg.CarouselID,
		arg.PhotoID,
		arg.DisplayText,
		arg.DisplayOrder,
	)
	var i CarouselPhoto
	err := row.Scan(
		&i.ID,
		&i.CarouselID,
		&i.PhotoID,
		&i.DisplayText,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCarouselPhoto = `-- name: DeleteCarouselPhoto :exec
DELETE FROM carousel_photos
WHERE id = $1
`

func (q *Queries) DeleteCarouselPhoto(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCarouselPhoto, id)
	return err
}

const getCarouselPhotoByID = `-- name: GetCarouselPhotoByID :one
SELECT id, carousel_id, photo_id, display_text, display_order, created_at
FROM carousel_photos
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCarouselPhotoByID(ctx context.Context, id int32) (CarouselPhoto, error) {
	row := q.db.QueryRow(ctx, getCarouselPhotoByID, id)
	var i CarouselPhoto
	err := row.Scan(
		&i.ID,
		&i.CarouselID,
		&i.PhotoID,
		&i.DisplayText,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getCarouselPhotosByCarouselID = `-- name: GetCarouselPhotosByCarouselID :many
SELECT
    cp.id,
    cp.carousel_id,
    cp.photo_id,
    cp.display_text,
    cp.display_order,
    cp.created_at,
    p.image_url,
    p.alt_text
FROM carousel_photos cp
JOIN photos p ON p.id = cp.photo_id
WHERE cp.carousel_id = $1
ORDER BY cp.display_order ASC
`

type GetCarouselPhotosByCarouselIDRow struct {
	ID           int32              `json:"id"`
	CarouselID   int32              `json:"carousel_id"`
	PhotoID      int32              `json:"photo_id"`
	DisplayText  pgtype.Text        `json:"display_text"`
	DisplayOrder pgtype.Int4        `json:"display_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ImageUrl     string             `json:"image_url"`
	AltText      pgtype.Text        `json:"alt_text"`
}

func (q *Queries) GetCarouselPhotosByCarouselID(ctx context.Context, carouselID int32) ([]GetCarouselPhotosByCarouselIDRow, error) {
	rows, err := q.db.Query(ctx, getCarouselPhotosByCarouselID, carouselID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCarouselPhotosByCarouselIDRow{}
	for rows.Next() {
		var i GetCarouselPhotosByCarouselIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CarouselID,
			&i.PhotoID,
			&i.DisplayText,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.ImageUrl,
			&i.AltText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderCarouselPhoto = `-- name: ReorderCarouselPhoto :exec
UPDATE carousel_photos
SET display_order = $2
WHERE id = $1
`

type ReorderCarouselPhotoParams struct {
	ID           int32       `json:"id"`
	DisplayOrder pgtype.Int4 `json:"display_order"`
}

func (q *Queries) ReorderCarouselPhoto(ctx context.Context, arg ReorderCarouselPhotoParams) error {
	_, err := q.db.Exec(ctx, reorderCarouselPhoto, arg.ID, arg.DisplayOrder)
	return err
}

const updateCarouselPhoto = `-- name: UpdateCarouselPhoto :one
UPDATE carousel_photos
SET
    display_text = $2,
    display_order = $3
WHERE id = $1
RETURNING id, carousel_id, photo_id, display_text, display_order, created_at
`

type UpdateCarouselPhotoParams struct {
	ID           int32       `json:"id"`
	DisplayText  pgtype.Text `json:"display_text"`
	DisplayOrder pgtype.Int4 `json:"display_order"`
}

func (q *Queries) UpdateCarouselPhoto(ctx context.Context, arg UpdateCarouselPhotoParams) (CarouselPhoto, error) {
	row := q.db.QueryRow(ctx, updateCarouselPhoto, arg.ID, arg.DisplayText, arg.DisplayOrder)
	var i CarouselPhoto
	err := row.Scan(
		&i.ID,
		&i.CarouselID,
		&i.PhotoID,
		&i.DisplayText,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}
