// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: institute.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInstitute = `-- name: CreateInstitute :one
INSERT INTO institutes (
    name,
    code,
    email,
    phone,
    address,
    is_active
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, name, code, email, phone, address, is_active, created_at, updated_at
`

type CreateInstituteParams struct {
	Name     string      `json:"name"`
	Code     string      `json:"code"`
	Email    pgtype.Text `json:"email"`
	Phone    pgtype.Text `json:"phone"`
	Address  pgtype.Text `json:"address"`
	IsActive pgtype.Bool `json:"is_active"`
}

func (q *Queries) CreateInstitute(ctx context.Context, arg CreateInstituteParams) (Institute, error) {
	row := q.db.QueryRow(ctx, createInstitute,
		arg.Name,
		arg.Code,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.IsActive,
	)
	var i Institute
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInstitute = `-- name: DeleteInstitute :exec
DELETE FROM institutes
WHERE id = $1
`

func (q *Queries) DeleteInstitute(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteInstitute, id)
	return err
}

const disableInstitute = `-- name: DisableInstitute :exec
UPDATE institutes
SET is_active = false
WHERE id = $1
`

func (q *Queries) DisableInstitute(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, disableInstitute, id)
	return err
}

const getAllInstitutes = `-- name: GetAllInstitutes :many
SELECT id, name, code, email, phone, address, is_active, created_at, updated_at
FROM institutes
WHERE is_active = true
ORDER BY created_at DESC
`

func (q *Queries) GetAllInstitutes(ctx context.Context) ([]Institute, error) {
	rows, err := q.db.Query(ctx, getAllInstitutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Institute{}
	for rows.Next() {
		var i Institute
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInstituteByCode = `-- name: GetInstituteByCode :one
SELECT id, name, code, email, phone, address, is_active, created_at, updated_at
FROM institutes
WHERE code = $1
AND is_active = true
LIMIT 1
`

func (q *Queries) GetInstituteByCode(ctx context.Context, code string) (Institute, error) {
	row := q.db.QueryRow(ctx, getInstituteByCode, code)
	var i Institute
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstituteByID = `-- name: GetInstituteByID :one
SELECT id, name, code, email, phone, address, is_active, created_at, updated_at
FROM institutes
WHERE id = $1
AND is_active = true
LIMIT 1
`

func (q *Queries) GetInstituteByID(ctx context.Context, id int32) (Institute, error) {
	row := q.db.QueryRow(ctx, getInstituteByID, id)
	var i Institute
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInstitute = `-- name: UpdateInstitute :one
UPDATE institutes
SET
    name = $2,
    code = $3,
    email = $4,
    phone = $5,
    address = $6,
    is_active = $7
WHERE id = $1
RETURNING id, name, code, email, phone, address, is_active, created_at, updated_at
`

type UpdateInstituteParams struct {
	ID       int32       `json:"id"`
	Name     string      `json:"name"`
	Code     string      `json:"code"`
	Email    pgtype.Text `json:"email"`
	Phone    pgtype.Text `json:"phone"`
	Address  pgtype.Text `json:"address"`
	IsActive pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdateInstitute(ctx context.Context, arg UpdateInstituteParams) (Institute, error) {
	row := q.db.QueryRow(ctx, updateInstitute,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.IsActive,
	)
	var i Institute
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
