// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notice.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotice = `-- name: CreateNotice :one
INSERT INTO notices (
    institute_id,
    title,
    description,
    is_published,
    publish_date
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, institute_id, title, description, is_published, publish_date, created_at
`

type CreateNoticeParams struct {
	InstituteID int32       `json:"institute_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	IsPublished pgtype.Bool `json:"is_published"`
	PublishDate pgtype.Date `json:"publish_date"`
}

func (q *Queries) CreateNotice(ctx context.Context, arg CreateNoticeParams) (Notice, error) {
	row := q.db.QueryRow(ctx, createNotice,
		arg.InstituteID,
		arg.Title,
		arg.Description,
		arg.IsPublished,
		arg.PublishDate,
	)
	var i Notice
	err := row.Scan(
		&i.ID,
		&i.InstituteID,
		&i.Title,
		&i.Description,
		&i.IsPublished,
		&i.PublishDate,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotice = `-- name: DeleteNotice :exec
DELETE FROM notices
WHERE id = $1
`

func (q *Queries) DeleteNotice(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteNotice, id)
	return err
}

const getNotice = `-- name: GetNotice :one
SELECT id, institute_id, title, description, is_published, publish_date, created_at
FROM notices
WHERE id = $1 AND institute_id = $2
LIMIT 1
`

type GetNoticeParams struct {
	ID          int32 `json:"id"`
	InstituteID int32 `json:"institute_id"`
}

func (q *Queries) GetNotice(ctx context.Context, arg GetNoticeParams) (Notice, error) {
	row := q.db.QueryRow(ctx, getNotice, arg.ID, arg.InstituteID)
	var i Notice
	err := row.Scan(
		&i.ID,
		&i.InstituteID,
		&i.Title,
		&i.Description,
		&i.IsPublished,
		&i.PublishDate,
		&i.CreatedAt,
	)
	return i, err
}

const getNoticesByInstitute = `-- name: GetNoticesByInstitute :many
SELECT id, institute_id, title, description, is_published, publish_date, created_at
FROM notices
WHERE institute_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetNoticesByInstitute(ctx context.Context, instituteID int32) ([]Notice, error) {
	rows, err := q.db.Query(ctx, getNoticesByInstitute, instituteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notice{}
	for rows.Next() {
		var i Notice
		if err := rows.Scan(
			&i.ID,
			&i.InstituteID,
			&i.Title,
			&i.Description,
			&i.IsPublished,
			&i.PublishDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchNotices = `-- name: SearchNotices :many
SELECT id, institute_id, title, description, is_published, publish_date, created_at
FROM notices
WHERE institute_id = $1
AND title ILIKE '%' || $2 || '%'
ORDER BY created_at DESC
`

type SearchNoticesParams struct {
	InstituteID int32       `json:"institute_id"`
	Column2     pgtype.Text `json:"column_2"`
}

func (q *Queries) SearchNotices(ctx context.Context, arg SearchNoticesParams) ([]Notice, error) {
	rows, err := q.db.Query(ctx, searchNotices, arg.InstituteID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notice{}
	for rows.Next() {
		var i Notice
		if err := rows.Scan(
			&i.ID,
			&i.InstituteID,
			&i.Title,
			&i.Description,
			&i.IsPublished,
			&i.PublishDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotice = `-- name: UpdateNotice :one
UPDATE notices
SET
    title = $2,
    description = $3,
    is_published = $4,
    publish_date = $5
WHERE id = $1
RETURNING id, institute_id, title, description, is_published, publish_date, created_at
`

type UpdateNoticeParams struct {
	ID          int32       `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	IsPublished pgtype.Bool `json:"is_published"`
	PublishDate pgtype.Date `json:"publish_date"`
}

func (q *Queries) UpdateNotice(ctx context.Context, arg UpdateNoticeParams) (Notice, error) {
	row := q.db.QueryRow(ctx, updateNotice,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.IsPublished,
		arg.PublishDate,
	)
	var i Notice
	err := row.Scan(
		&i.ID,
		&i.InstituteID,
		&i.Title,
		&i.Description,
		&i.IsPublished,
		&i.PublishDate,
		&i.CreatedAt,
	)
	return i, err
}
