// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: photos.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPhoto = `-- name: CreatePhoto :one
INSERT INTO photos (
    image_url,
    alt_text,
    uploaded_by
) VALUES (
    $1, $2, $3
)
RETURNING id, image_url, alt_text, uploaded_by, created_at
`

type CreatePhotoParams struct {
	ImageUrl   string      `json:"image_url"`
	AltText    pgtype.Text `json:"alt_text"`
	UploadedBy int32       `json:"uploaded_by"`
}

func (q *Queries) CreatePhoto(ctx context.Context, arg CreatePhotoParams) (Photo, error) {
	row := q.db.QueryRow(ctx, createPhoto, arg.ImageUrl, arg.AltText, arg.UploadedBy)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.ImageUrl,
		&i.AltText,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deletePhoto = `-- name: DeletePhoto :exec
DELETE FROM photos
WHERE id = $1
`

func (q *Queries) DeletePhoto(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePhoto, id)
	return err
}

const getAllPhotos = `-- name: GetAllPhotos :many
SELECT id, image_url, alt_text, uploaded_by, created_at
FROM photos
ORDER BY created_at DESC
`

func (q *Queries) GetAllPhotos(ctx context.Context) ([]Photo, error) {
	rows, err := q.db.Query(ctx, getAllPhotos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Photo{}
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.ImageUrl,
			&i.AltText,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPhotoByID = `-- name: GetPhotoByID :one
SELECT id, image_url, alt_text, uploaded_by, created_at
FROM photos
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPhotoByID(ctx context.Context, id int32) (Photo, error) {
	row := q.db.QueryRow(ctx, getPhotoByID, id)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.ImageUrl,
		&i.AltText,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPhotosByUser = `-- name: GetPhotosByUser :many
SELECT id, image_url, alt_text, uploaded_by, created_at
FROM photos
WHERE uploaded_by = $1
ORDER BY created_at DESC
`

func (q *Queries) GetPhotosByUser(ctx context.Context, uploadedBy int32) ([]Photo, error) {
	rows, err := q.db.Query(ctx, getPhotosByUser, uploadedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Photo{}
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.ImageUrl,
			&i.AltText,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePhoto = `-- name: UpdatePhoto :one
UPDATE photos
SET
    image_url = $2,
    alt_text = $3
WHERE id = $1
RETURNING id, image_url, alt_text, uploaded_by, created_at
`

type UpdatePhotoParams struct {
	ID       int32       `json:"id"`
	ImageUrl string      `json:"image_url"`
	AltText  pgtype.Text `json:"alt_text"`
}

func (q *Queries) UpdatePhoto(ctx context.Context, arg UpdatePhotoParams) (Photo, error) {
	row := q.db.QueryRow(ctx, updatePhoto, arg.ID, arg.ImageUrl, arg.AltText)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.ImageUrl,
		&i.AltText,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}
