// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: photos.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPhoto = `-- name: CreatePhoto :one
INSERT INTO photos (
    image_url,
    alt_text,
    uploaded_by,
    institute_id
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, image_url, alt_text, uploaded_by, created_at, institute_id, cloudinary_public_id
`

type CreatePhotoParams struct {
	ImageUrl    string      `json:"image_url"`
	AltText     pgtype.Text `json:"alt_text"`
	UploadedBy  int32       `json:"uploaded_by"`
	InstituteID int32       `json:"institute_id"`
}

func (q *Queries) CreatePhoto(ctx context.Context, arg CreatePhotoParams) (Photo, error) {
	row := q.db.QueryRow(ctx, createPhoto,
		arg.ImageUrl,
		arg.AltText,
		arg.UploadedBy,
		arg.InstituteID,
	)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.ImageUrl,
		&i.AltText,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.InstituteID,
		&i.CloudinaryPublicID,
	)
	return i, err
}

const deletePhoto = `-- name: DeletePhoto :exec
DELETE FROM photos
WHERE id = $1
AND institute_id = $2
`

type DeletePhotoParams struct {
	ID          int32 `json:"id"`
	InstituteID int32 `json:"institute_id"`
}

func (q *Queries) DeletePhoto(ctx context.Context, arg DeletePhotoParams) error {
	_, err := q.db.Exec(ctx, deletePhoto, arg.ID, arg.InstituteID)
	return err
}

const getPhotoByID = `-- name: GetPhotoByID :one
SELECT id, image_url, alt_text, uploaded_by, created_at, institute_id, cloudinary_public_id
FROM photos
WHERE id = $1
AND institute_id = $2
LIMIT 1
`

type GetPhotoByIDParams struct {
	ID          int32 `json:"id"`
	InstituteID int32 `json:"institute_id"`
}

func (q *Queries) GetPhotoByID(ctx context.Context, arg GetPhotoByIDParams) (Photo, error) {
	row := q.db.QueryRow(ctx, getPhotoByID, arg.ID, arg.InstituteID)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.ImageUrl,
		&i.AltText,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.InstituteID,
		&i.CloudinaryPublicID,
	)
	return i, err
}

const getPhotosByInstitute = `-- name: GetPhotosByInstitute :many
SELECT id, image_url, alt_text, uploaded_by, created_at, institute_id, cloudinary_public_id
FROM photos
WHERE institute_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetPhotosByInstitute(ctx context.Context, instituteID int32) ([]Photo, error) {
	rows, err := q.db.Query(ctx, getPhotosByInstitute, instituteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Photo{}
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.ImageUrl,
			&i.AltText,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.InstituteID,
			&i.CloudinaryPublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPhotosByUser = `-- name: GetPhotosByUser :many
SELECT id, image_url, alt_text, uploaded_by, created_at, institute_id, cloudinary_public_id
FROM photos
WHERE uploaded_by = $1
AND institute_id = $2
ORDER BY created_at DESC
`

type GetPhotosByUserParams struct {
	UploadedBy  int32 `json:"uploaded_by"`
	InstituteID int32 `json:"institute_id"`
}

func (q *Queries) GetPhotosByUser(ctx context.Context, arg GetPhotosByUserParams) ([]Photo, error) {
	rows, err := q.db.Query(ctx, getPhotosByUser, arg.UploadedBy, arg.InstituteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Photo{}
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.ImageUrl,
			&i.AltText,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.InstituteID,
			&i.CloudinaryPublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePhotoImage = `-- name: UpdatePhotoImage :one
UPDATE photos
SET
    image_url = $3,
    cloudinary_public_id = $4,
    updated_at = now()
WHERE id = $1
AND institute_id = $2
RETURNING id, image_url, alt_text, uploaded_by, created_at, institute_id, cloudinary_public_id
`

type UpdatePhotoImageParams struct {
	ID                 int32       `json:"id"`
	InstituteID        int32       `json:"institute_id"`
	ImageUrl           string      `json:"image_url"`
	CloudinaryPublicID pgtype.Text `json:"cloudinary_public_id"`
}

func (q *Queries) UpdatePhotoImage(ctx context.Context, arg UpdatePhotoImageParams) (Photo, error) {
	row := q.db.QueryRow(ctx, updatePhotoImage,
		arg.ID,
		arg.InstituteID,
		arg.ImageUrl,
		arg.CloudinaryPublicID,
	)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.ImageUrl,
		&i.AltText,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.InstituteID,
		&i.CloudinaryPublicID,
	)
	return i, err
}
