// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgdb

import (
	"context"
)

type Querier interface {
	Login(ctx context.Context, arg LoginParams) (LoginRow, error)
}

var _ Querier = (*Queries)(nil)
