// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    institute_id,
    name,
    email,
    password,
    role,
    is_active
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, institute_id, name, email, password, role, is_active, created_at, updated_at
`

type CreateUserParams struct {
	InstituteID int32       `json:"institute_id"`
	Name        string      `json:"name"`
	Email       string      `json:"email"`
	Password    string      `json:"password"`
	Role        pgtype.Text `json:"role"`
	IsActive    pgtype.Bool `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.InstituteID,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Role,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.InstituteID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const disableUser = `-- name: DisableUser :exec
UPDATE users
SET is_active = false
WHERE id = $1
`

func (q *Queries) DisableUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, disableUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, institute_id, name, email, password, role, is_active, created_at, updated_at
FROM users
WHERE email = $1
  AND institute_id = $2
LIMIT 1
`

type GetUserByEmailParams struct {
	Email       string `json:"email"`
	InstituteID int32  `json:"institute_id"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.Email, arg.InstituteID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.InstituteID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, institute_id, name, email, password, role, is_active, created_at, updated_at
FROM users
WHERE id = $1
AND institute_id = $2
LIMIT 1
`

type GetUserByIDParams struct {
	ID          int32 `json:"id"`
	InstituteID int32 `json:"institute_id"`
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.ID, arg.InstituteID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.InstituteID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsersByInstitute = `-- name: GetUsersByInstitute :many
SELECT id, institute_id, name, email, password, role, is_active, created_at, updated_at
FROM users
WHERE institute_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetUsersByInstitute(ctx context.Context, instituteID int32) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByInstitute, instituteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.InstituteID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loginUser = `-- name: LoginUser :one
SELECT id, institute_id, name, email, password, role, is_active, created_at, updated_at
FROM users
WHERE (id = $1 OR email = $2)
AND is_active = true
LIMIT 1
`

type LoginUserParams struct {
	ID    int32  `json:"id"`
	Email string `json:"email"`
}

func (q *Queries) LoginUser(ctx context.Context, arg LoginUserParams) (User, error) {
	row := q.db.QueryRow(ctx, loginUser, arg.ID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.InstituteID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    name = $2,
    role = $3,
    is_active = $4,
    updated_at = now()
WHERE id = $1
  AND institute_id = $5
RETURNING id, institute_id, name, email, password, role, is_active, created_at, updated_at
`

type UpdateUserParams struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Role        pgtype.Text `json:"role"`
	IsActive    pgtype.Bool `json:"is_active"`
	InstituteID int32       `json:"institute_id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Role,
		arg.IsActive,
		arg.InstituteID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.InstituteID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password = $2
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID       int32  `json:"id"`
	Password string `json:"password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.Password)
	return err
}
